### ISSUE TITLE
issues with Import Zoom Attendance

### ISSUE THREAD

**Issue by dragonxtek** [CUBoulder-OIT/canvas-userscripts#7]
Hi, 
I follow the steps in [https://oit.colorado.edu/tutorial/import-zoom-attendance-canvas-gradebook](https://oit.colorado.edu/tutorial/import-zoom-attendance-canvas-gradebook), but Canvas does not recognize any user.
Something strange is that it tells me that the users are not recognized, since the names that it prints to me correspond to the mail (without at and without domain) not to user names as shown in step 9.
Could it be that it is misextracting the data to compare them?
Inside the csv are the same names of users and mails that in canvas, for that reason I imagine that it must be obtaining the data badly from the script
![Selection_999(640)](https://user-images.githubusercontent.com/10552658/91328976-9be76d00-e795-11ea-9982-5cfd717e2e06.png)

**Comment by jashbycu** [comment]
Hi, and sorry for the delayed response. At CU Boulder we have to strip the domains from the usernames. If your school doesn't do that, then the previous version of the script would fail for that reason. I just made an update though in the latest commit that should fix this: now the script will try matching users with and without the domain name so that it will work either way.
